<?php

namespace Lottery\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * DrawScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrawScoreRepository extends EntityRepository
{
    public function getPagedResults($offset = 0, $limit = 10)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('score')
            ->from('Lottery\Entity\DrawScore', 'score')
            ->where('score.visible = ?1')
            ->orderBy('score.drawTime', 'DESC')
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->setParameter(1, true);

        $query = $qb->getQuery();

        $paginator = new Paginator($query);

        return $paginator;
    }
    public function countPages($limit){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('count(score.drawScoreId)')
            ->from('Lottery\Entity\DrawScore', 'score')
            ->where('score.visible = ?1')
            ->setParameter(1, true);
        $amount = $qb->getQuery()->getSingleScalarResult();

        $result = ceil($amount / $limit);
        return $result;
    }
}
